# -*- coding: utf-8 -*-
"""Reforço.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w8JJvCbB5GAgxZ_rD-QHeub7a-iOW3pm

**LISTA DE EXERCÍCIOS**
"""

#Leia dois números, faça a soma e apresente caso seja maior que 15.
numero1= float(input("digite a nota1"))
numero2= float(input("digite a nota2"))
soma=(numero1+numero2)
if soma > 15:
  print("Resultado da soma:",soma)
else:
  print("A soma dos números não é maior que.")

#2. Faça um programa que recebendo um valor inteiro, informe se o número é positivo, negativo ou neutro.
numero= float(input("digite o numero"))
if numero > 0:
  print("positivo")
elif numero < 0:
  print("negativo")
else:
  print("neutro")

#3. Leia a idade e informe se a pessoa é maior ou menor de idade
idade= int(input("digite a idade"))
if idade >= 18:
  print("Maior de idade")
else: #else é tudo que fica fora, que não tem mais condições
  print("Menor de idade")

#4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.
temperatura= float(input("Qual a temperatura atual?"))
if temperatura >=25:
  print("Quente")
elif temperatura <25 and temperatura >19: #elif pode utilizar várias vezes
  print ("agradável")
else:
  print("frio")

#5. Faça um programa em linguagem Python que leia dois números inteiros e informe se estes são iguais ou diferentes.
numero1= int(input("digite primeiro numero"))
numero2: int(input("digite segundo numero"))
if numero1 == numero2:
  print("numero igual")
else:
  print("numero diferente")

# 6. Escreva um programa que verifique a validade de uma senha fornecida pelo usuário. A senha válida é o número 1234. Devem ser impressas as seguintes mensagens:
# ACESSO PERMITIDO caso a senha seja válida.
# ACESSO NEGADO caso a senha seja inválida
senha= float(input("digite a senha"))
correta= 1234
if senha == correta:
  print("Acesso permitido")
else:
  print("Acesso negado")

#7. Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou igual a 7, informar que o aluno foi aprovado;
#se a média for maior ou igual a 5 mas menor do que 7, informar que o aluno está de exame;
#se a média for menor do que 5 informar que o aluno foi reprovado.
nota1= float(input("Ler nota 1"))
nota2= float(input("Ler nota 2"))
media= (nota1 + nota2)/2
if media >= 7:
  print("Aprovado")
elif media >=5 and media <7:
  print("Aluno em exame")
else:
  print("Reprovado")

#8 8. Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os gols de cada time) e informe se o resultado foi um empate, se a vitória foi do
#primeiro time ou do segundo time
Time1= float(input("Digite o gol do time A:"))
Time2= float(input("Digite o gol do time B:"))
if Time1 > Time2:
  print("Vitoria time1")
elif Time2 > Time1:
  print("Vitoria time2")
else:
  print("Empate")

#9 . Faça um Programa que pergunte em que turno você estuda. Peça para digitar
# M-matutino ou V-Vespertino ou N- Noturno.
#Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.
Jornada= str(input("Em que turno você trabalha?")).upper() #upper converte em maiuscula o texto digitado
Matutino= "M"
Vespertino= "V"
Noturno= "N"
if Jornada == Matutino:
  print("Bom dia!")
elif Jornada == Vespertino:
  print("Boa tarde!")
elif Jornada == Noturno:
  print("Boa noite!")
else:
  print ("Valor inválido")

#10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a classificação etária de acordo com as faixas de valores:
# Criança para 0 até 11 anos;
# Adolescente para 12 até 18 anos;
# Jovem para 19 até 24 anos;
# Adulto para 25 até 40 anos;
# Meia Idade para 41 até 60 anos;
# Idoso acima de 60 anos.
idade= int(input("Qual sua idade"))
if idade >= 0 and idade <=11:
  print("Criança")
elif idade >= 12 and idade <= 18:
  print("Adolescente")
elif idade >= 19 and idade <= 24:
  print("Jovem")
elif idade >= 25 and idade <= 40:
  print("Adulto")
elif idade >= 41 and idade <= 60:
  print("Meia idade")
else:
  print("Idoso")

#11. As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes.
#Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
# salários até R$ 280,00 (incluindo) : aumento de 20%
# salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
# salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
# salários de R$ 1500,00 em diante : aumento de 5%
#Após o aumento ser realizado, informe na tela:
# o salário antes do reajuste;
# o percentual de aumento aplicado;
# o valor do aumento;
# o novo salário, após o aumento.

#12. Faça um Programa que leia um número e exiba o dia correspondente da semana.
#(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.
Ler_numero= int(input("Qual dia corresponde da semana?"))
if Ler_numero == 1:
  print ("Domingo")
elif Ler_numero == 2:
  print("Segunda Feira")
elif Ler_numero == 3:
  print ("Terça Feira")
elif Ler_numero == 4:
  print ("Quarta Feira")
elif Ler_numero == 5:
  print ("Quinta Feira")
elif Ler_numero == 6:
  print ("Sexta Feira")
elif Ler_numero == 7:
  print ("Sábado")
else:
  print("Número digitado não corresponde a dia da semana, corrija o dado")

# 13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta do usuário, faça a devida conversão.
Escolha_tipo_temp= input("Quer passar a temperatura de Fahrenheit para Celsius (digite 'FC') ou Celsius para Fahrenheit (digite 'CF')?").upper()
Converter_tempera: float(input("Quer passar a temperatura Fahrenheit para Celsius?"))
calculo_Celsius= (5/9*(f-32))
Calculo_Fahrenheit= ((9/5)*(c+32))
if Escolha_tipo_temp == 'FC' : calculo_Celsius:
  print(f"A temperatura em Celsius é:{calculo_Celsius:.2f}ºC")
elif Escolha_tipo_temp == 'CF' : Calculo_Fahrenheit:
  print(f"A temperatura em Fahrenheit é: {Calculo_Fahrenheit:.2f}ºC")

#14. Faça um programa que receba a idade de uma pessoa e imprima sua condição (obrigatória, optativa ou proibida), em relação ao ato de votar, conforme apresentado abaixo:
# Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
# Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar (optativo);
# Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar (obrigatório);
# Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).
idade= float(input("Digite a idade?"))
if idade <16:
    print("Proibido votar")
elif  16 <= idade < 18:
    print("Optativo")
elif idade >=65:
    print("Optativo")
else:
    print("Obrigatório")

#15. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:
# “Telefonou para a vítima? “
# “Esteve no local do crime?”
# “Mora perto da vítima? “
## “Devia para a vítima? “
# “Já trabalhou com a vítima?
#16 programa deve no final emitir uma classificação sobre a participação da pessoa no crime.
#Se a pessoa responder positivamente a 2 questões ela deve ser classificada como “Suspeita”,
# entre 3 e 4 como “Cúmplice”
# 5 como “Assassino“.
#Caso contrário, ele será classificado como “Inocente“.
print ("Responda as seguintes questões?")
Pergunta1= input("Telefonou para vitima?").lower () #.lower serve para transformar tudo para minusculo
Pergunta2= input("Esteve no local do crime?").lower () #
Pergunta3= input("Mora perto da vitima?").lower()
Pergunta4= input("Devia para vitima?").lower ()
Pergunta5= input("Ja trabalhou com a vitima?").lower ()
positivas = 0 # porque o python começa sempre com 0
if Pergunta1 == "Sim":
  positivas += 1
if Pergunta2 == "Sim":
  positivas += 1
if Pergunta3 == "Sim":
  positivas += 1
if Pergunta4 == "Sim":
  positivas += 1
if Pergunta5 == "Sim":
  positivas += 1

if positivas == 2:
  print ("Suspeita")
elif positivas >=3 and positivas <=4:
  print ("Cumplice")
elif positivas ==5:
  print ("assassino")
else:
  print("inocente")

#17. Faça um programa que pergunte o preço de três produtos
#e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato.
Produto1= float(input("Qual o preço do produto1?"))
Produto2= float(input("Qual o preço do produto2?"))
Produto3= float(input("Qual o preço do produto3?"))
if Produto1 < Produto2 and Produto1 < Produto3:
    print("Comprar produto 1")
elif Produto2 < Produto1 and Produto2 < Produto3:
    print("Comprar produto 2")
else:
    print("Comprar produto 3")