# -*- coding: utf-8 -*-
"""4 listao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/161KSpq0GGoxJ7GXEZc-cW8Z7ZSjBxYmk
"""

# 1. Leia dois números, faça a soma e apresente caso seja maior que 15.
numero1= float(input("digite primeiro numero"))
numero2= float(input("digite segundo numero"))
soma= numero1 + numero2
if soma >15:
  print("resultado maior 15",soma)
else:
  print("resultado menor15")



# 2. Faça um programa que recebendo um valor inteiro, informe se o número é positivo, negativo ou neutro.

numero= int(input("me informe um numero"))
if numero <0:
  print("resultado negativo")
elif numero == 0:
  print("neutro")
else:
  print("resultado positivo")

# 3. Leia a idade e informe se a pessoa é maior ou menor de idade.

idade= int(input("qual a sua idade"))
if idade >18:
 print("maior de idade")
elif idade <17:
 print("menor de idade")

# 4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.

temperatura_ambiente = float(input("qual a temperatuta ambiente"))
if temperatura_ambiente <=10:
  print("esta frio")
elif temperatura_ambiente >=11 and temperatura_ambiente <=20:
  print("agradavel")
else:
    print("esta calor")

# 5. Faça um programa em linguagem Python que leia dois números inteiros e informe se estes são iguais ou diferentes.
numero1 = int(input("digite o primeiro numero"))
numero2 = int(input("digite o segundo numero"))
if numero1 == numero2:
  print("numeros iguais")
else:
  print("numeros diferente")

# 6. Escreva um programa que verifique a validade de uma senha fornecida pelo usuário. A senha válida é o número 1234. Devem ser impressas as seguintes mensagens:  ACESSO PERMITIDO caso a senha seja válida.  ACESSO NEGADO caso a senha seja inválida.

pergunta= float(input("digite a senha"))
senha = "1234"
if pergunta == senha:
  print("acsso permitido")
else:
    print("acesso negado")

# 7. Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas menor do que 7, informar que o aluno está de exame; se a média for menor do que 5 informar que o aluno foi reprovado.
nota1 = float(input("por favor digite nota1"))
nota2 = float(input("por favor digite nota2"))
media =(nota1 + nota2)/2
if  media >=7:
  print("aprovado")
elif media >=5 and media <7:
  print("recuperacao")
else:
  print("reprovado")

# 8. Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os gols de cada time) e informe se o resultado foi um empate, se a vitória foi do primeiro time ou do segundo time.

timeA = int(input("digite o gol A"))
timeB = int(input("digite o gol B"))
if timeA == timeB:
  print("empate")
elif timeA>timeB:
  print("vitória foi do primeiro time")
else:
  print("vitoria do segundo time")

from re import M
# 9. Faça um Programa que pergunte em que turno você estuda. Peça para digitar Mmatutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.
turno = str(input("qual turno voce estuda")).upper()
Matutino= "M"
vespertino= "V"
noturno= "N"
if turno == Matutino:
  print("bom dia")
elif turno == vespertino:
  print("boa tarde")
elif turno == noturno:
  print("boa noite")
else:
  print("valor invalido")

# 10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a classificação etária de acordo com as faixas de valores:  Criança para 0 até 11 anos;  Adolescente para 12 até 18 anos;  Jovem para 19 até 24 anos;  Adulto para 25 até 40 anos;  Meia Idade para 41 até 60 anos;  Idoso acima de 60 anos.

idade = int(input("qual a sua idade?"))
if idade>=0 and idade<=11:
  print("criança")
elif idade>=12 and idade<=18:
  print("adolecente")
elif idade>=19 and idade<=24:
  print("jovem")
elif idade>=25 and idade<=40:
  print("adulto")
elif idade>=41 and idade<=60:
  print("meia idade")
else:
  print("idoso")

# 11. As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual: salários até R$ 280,00 (incluindo) : aumento de 20% salários entre R$ 280,00 e R$ 700,00 : aumento de 15% salários entre R$ 700,00 e R$ 1500,00 : aumento de 10% salários de R$ 1500,00 em diante : aumento de 5% de Após o aumento ser realizado, informe na tela: o salário antes do reajuste; o percentual de aumento aplicado; o valor do aumento; o novo salário, após o aumento.

def calcular_reajuste(salario):
    if salario <= 280:
        percentual_aumento = 20
elif salario <= 700:
        percentual_aumento = 15
elif salario <= 1500:
        percentual_aumento = 10
else:
        percentual_aumento = 5

    aumento = salario * (percentual_aumento / 100)
    novo_salario = salario + aumento

    return percentual_aumento, aumento, novo_salario

salario_atual=  float(input("Digite o salário do colaborador:"))

percentual, valor_aumento, novo_salario = calcular_reajuste(salario_atual)

print(f"Salário antes do reajuste: R$ {salario_atual:.2f}")
print(f"Percentual de aumento aplicado: {percentual}%")
print(f"Valor do aumento: R$ {valor_aumento:.2f}")
print(f"Novo salário, após o aumento: R$ {novo_salario:.2f}")

# 12.Faça um Programa que leia um número e exiba o dia correspondente da semana.(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.
semana= int(input("digite o numero que corresponde ao dia da semana"))
if semana == 1:
  print("domingo")
elif semana == 2:
    print("coragem")
elif semana == 3:
      print("força na peruca")
elif semana == 4:
        print("força")
elif semana == 5:
          print("ta chegando")
else:
            print("sextooo")

# 13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta do usuário, faça a devida conversão.


def fahrenheit_para_celsius(fahrenheit):
    celsius = (fahrenheit - 32) * 5/9
    return celsius

def celsius_para_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

def main():
    escolha = input("Você quer converter de Fahrenheit para Celsius (digite 'F') ou de Celsius para Fahrenheit (digite 'C')? ").upper()

    if escolha == 'F':
        fahrenheit = float(input("Digite a temperatura em Fahrenheit: "))
        celsius = fahrenheit_para_celsius(fahrenheit)
        print(f"A temperatura em Celsius é: {celsius:.2f}°C")
    elif escolha == 'C':
        celsius = float(input("Digite a temperatura em Celsius: "))
        fahrenheit = celsius_para_fahrenheit(celsius)
        print(f"A temperatura em Fahrenheit é: {fahrenheit:.2f}°F")
    else:
        print("Opção inválida. Por favor, escolha 'F' para Fahrenheit para Celsius ou 'C' para Celsius para Fahrenheit.")

if __name__ == "__main__":
    main()

# 14. Faça um programa que receba a idade de uma pessoa e imprima sua condição (obrigatória, optativa ou proibida), em relação ao ato de votar, conforme apresentado abaixo:  Pessoas com idade menor que 16 anos são proibidas de votar (proibido);  Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar (optativo);  Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar (obrigatório);Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).

idade= float(input("digite sua idade"))
if idade <16:
  print("proibido votar")
elif 16 <= idade < 18:
    print("optativo")
elif idade >= 65:
  print("optativo")
else:
  print("obrigatorio")

# 15. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:  “Telefonou para a vítima? “   “Esteve no local do crime?”   “Mora perto da vítima? “   “Devia para a vítima? “  “Já trabalhou com a vítima? “Faça um Programa que leia um número e exiba o dia correspondente da semana.(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.

semana= int(input("digite o numero que corresponde ao dia da semana"))
if semana == 1:
  print("domingo")
elif semana == 2:
    print("coragem")
elif semana == 3:
      print("força na peruca")
elif semana == 4:
        print("força")
elif semana == 5:
          print("ta chegando")
else:
            print("sextoo
print("responda as seguintes perguntas com sim ou nao:")
pergunta1= input("telefonou para a vitima?").lower()
pergunta2= input("esteve no local do crime?").lower()
pergunta3= input("mora perto da vitima?").lower()
pergunta4= input("devia para vitima?").lower()
pergunta5= input("ja trabalhou com a vitima?").lower()

positiva=0

if pergunta1 == "sim":
  positiva +=1
if pergunta2 == "sim":
  positiva +=1
if pergunta3 == "sim":
  positiva +=1
if pergunta4 == "sim":
  positiva +=1
if pergunta5 == "sim":
  positiva +=1

if positiva == 2:
 print("suspeita")
#elif 3<=positivas<=4:
elif positiva>=3 and positiva<=4:
  print("cumplice")
elif positiva == 5:
    print("bandindinho")
else:
      print("inocente")

# 17. Faça um programa que pergunte o preço de três produtos e informe qual produtovocê deve comprar, sabendo que a decisão é sempre pelo mais barato.

produto1= float(input("qual o preço do produto1"))
produto2= float(input("qual o preço do produto2"))
produto3= float(input("qual o preço do produto3"))
if produto1 < produto2 and produto1 < produto3:
  print("comprar produto 1")
elif produto2 < produto1 and produto2 < produto3:
  print(" comprar produto 2")
else:
      print("comprar produto3")

# 18. desenvolver um botao para temperatura de bebidas no freezer para acelerar o resfriamento em 10 minutos.
#pseudocodigo
#desenvolver um botao.
#inclir contador de tempo
#deixar uma programação de alarme a cada 10 min
#ativamento atraves do usuario
#a partir do acionamento iniciar contagem
#tempo estimado,desejado,10 min
#apos terminodo o tempo,aviso sonoro 15 seg
# desligamento automatico,sem interferencia.

turbo= str(input("voce quer acionar o botao turbo?")).upper()
if turbo == "sim":
  print("aguarde")
else:
  print("deseja ativar")

# 19. Leia dois números, faça a soma e apresente caso seja maior que 15.
numero1= float(input("entre com a nota1:"))
numero2= float(input("entre com a nota2:"))
soma=(numero1 + numero2)
if soma > 15:
    print(soma)

# 20. Faça um programa que recebendo um valor inteiro, informe se o número é positivo, negativo ou neutro.
numero= float(input("digite o numero"))
if numero > 0:
  print("numero positivo")
elif numero < 0:
    print("numero negativo")
else:
      print("neutro")

# 21. Leia a idade e informe se a pessoa é maior ou menor de idade?
idade= int(input("digite a idade"))
if idade >=18:
  print("maior de 18 ")
else:
    print("menor de 18 ")

# 22.
frutas=["banana","laranja","uva","amexa"]
x1= "banana"
x2= "laranja"
x3= "abacaxi"

xresult= x1 in frutas
print(xresult)
xresult= x1 not in frutas
print(xresult)
xresult= x2 not in frutas
print(xresult)
xresult= x3 in frutas
print(xresult)

# 23.
x1="botafogo"
x2="flamengo"
x3="botafogo"
xresult=x1 is x3
print(xresult)
xresult=x1 is not x2
print(xresult)
xresult=x1 is x2
print(xresult)
xresult=x2 is not x3
print(xresult)



